# Generated by Django 4.2.1 on 2023-05-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_question_level_alter_student_dept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="level",
            field=models.CharField(
                choices=[("2", "general"), ("1", "easy"), ("3", "difficult")],
                max_length=10,
                verbose_name="等级",
            ),
        ),
    ]
